services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HahnSoftware@123
      - MSSQL_DATABASE=HahnSoftwareDb
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
  api:
    build:
      context: .
      dockerfile: src/HahnSoftware.API/Dockerfile
    ports:
      - "7276:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
  ui:
    build:
      context: ./src/HahnSoftware.UI
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
volumes:
  sqlserverdata:
