services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HahnSoftware@123
      - MSSQL_DATABASE=HahnSoftwareDb
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
  api:
    build:
      context: .
      dockerfile: src/HahnSoftware.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=HahnSoftwareDb;User=sa;Password=HahnSoftware@123;
    depends_on:
      - sqlserver
  ui:
    build:
      context: .
      dockerfile: src/HahnSoftware.UI/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
volumes:
  sqlserverdata:
